#!/bin/bash

mkdir -p build
cd build

if [ $# -ne 1 ];then
    echo "ERROR: Invalid number of arguments"
    echo "INFO: Provide -g argument to generate build files"
    echo "-b to build the project or"
    echo "-r to run the solver-rc executable"
    exit 1
fi

if [ $1 = "-g" ];
then
    cmake --fresh -DSOLVER_BUILD_TESTS=TRUE -DGLFW_BUILD_EXAMPLES=TRUE ..
elif [ $1 = "-b" ];
then
    cmake --build .
elif [ $1 = "-d" ];
then
    cmake -DCMAKE_BUILD_TYPE=Debug -DSOLVER_BUILD_TESTS=TRUE ..
    cmake --build .
elif [ $1 = "-r" ];
then
    ./src/solver-rc;
elif [ $1 = "-t" ];
then
    ctest -V ./tests
else
    exit 2
fi

cd - > /dev/null
exit 0
