#!/bin/bash

mkdir -p build
cd build

if [ $# -eq 0 ];then
    echo "ERROR: Invalid number of arguments"
    echo "INFO: Provide -g argument to generate build files"
    echo "-b to build the project or"
    echo "-r to run the solver-rc executable"
    exit 1
fi


if [ $1 = "-b" ];
then
    cmake --fresh -DGLFW_BUILD_EXAMPLES=TRUE ..
    cmake --build .
elif [ $1 = "-r" ];
then
    ./src/solver-rc;
elif [ $1 = "-t" ];
then
    cmake --fresh .. &&
    cmake --build . &&
    ctest --output-on-failure tests
else
    exit 2
fi

cd - > /dev/null
exit 0
